/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;
import service.KhachHangService;

/**
 *
 * @author ADMIN
 */
public class QuanLyKhachHang extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private KhachHangService service = new KhachHangService();

    public QuanLyKhachHang() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        loadTable();

    }

    public void loadTable() {
        model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        List<KhachHang> list = service.getAll();
        for (KhachHang s : list) {
            model.addRow(new Object[]{s.getMa(), s.getTen(), s.getGioiTinh(), s.getNgaySinh(), s.getEmail(), s.getSdt(), s.getSoCMT(), s.getDiaChi(), s.getDiemTichLuy(), doiTT(s.getTinhTrang())});

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        rdoHD = new javax.swing.JRadioButton();
        rdoKoHD = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        tbnLamMoi = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        txtDiaChi = new javax.swing.JTextField();
        lblDiem = new javax.swing.JLabel();
        txtCCCD = new javax.swing.JTextField();
        txtNgaySinh = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(250, 182, 124));
        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(1320, 810));

        jPanel2.setBackground(new java.awt.Color(250, 182, 124));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Mã:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));
        jPanel2.add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, 212, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Tên:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, -1));

        txtTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKeyReleased(evt);
            }
        });
        jPanel2.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, 212, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setText("Giới tính:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        buttonGroup2.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel2.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, -1, -1));

        buttonGroup2.add(rdoNu);
        rdoNu.setSelected(true);
        rdoNu.setText("Nữ");
        jPanel2.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel30.setText("Ngày sinh:");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel31.setText("Email:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, -1, 20));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 214, -1));
        txtEmail.getAccessibleContext().setAccessibleName("");

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setText("SĐT:");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));
        jPanel2.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 214, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel33.setText("Địa chỉ:");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, -1, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel34.setText("Điểm:");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel36.setText("Số CCCD:");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel37.setText("Trạng thái:");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 570, -1, -1));

        buttonGroup1.add(rdoHD);
        rdoHD.setText("Hoạt động");
        rdoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoHDActionPerformed(evt);
            }
        });
        jPanel2.add(rdoHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 100, -1));

        buttonGroup1.add(rdoKoHD);
        rdoKoHD.setSelected(true);
        rdoKoHD.setText("Không hoạt động");
        rdoKoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKoHDActionPerformed(evt);
            }
        });
        jPanel2.add(rdoKoHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 570, 120, -1));

        btnThem.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel2.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 440, -1, 34));

        btnXoa.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_updatecilent.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel2.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 490, 110, 34));

        btnSua.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_deletecilent.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel2.add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 110, 34));

        tbnLamMoi.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        tbnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_sendmail.png"))); // NOI18N
        tbnLamMoi.setText("Mail");
        tbnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnLamMoiActionPerformed(evt);
            }
        });
        jPanel2.add(tbnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 110, 34));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel38.setText("Quản lý khách hàng");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 320, -1));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Giới tính", "Ngày sinh", "Email", "Số điện thoại", "Số CCCD", "Địa chỉ", "Điểm", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblKhachHang);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 101, 1228, 299));
        jPanel2.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 290, -1));

        lblDiem.setText("0");
        jPanel2.add(lblDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 40, -1));
        jPanel2.add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 290, -1));

        txtNgaySinh.setDateFormatString("yyyy-MM-dd");
        txtNgaySinh.setDoubleBuffered(false);
        txtNgaySinh.setPreferredSize(new java.awt.Dimension(64, 22));
        jPanel2.add(txtNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 570, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKeyReleased

    private void rdoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoHDActionPerformed

    private void rdoKoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKoHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoKoHDActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        int gioiTinh = 1;
        if (rdoNam.isSelected()) {
            gioiTinh = 1;
        } else {
            gioiTinh = 0;
        }
        SimpleDateFormat dinhDang = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinh = dinhDang.format(txtNgaySinh.getDate());
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        String cccd = txtCCCD.getText();
        String diaChi = txtDiaChi.getText();
        int tinhTrang = 0;
        if (rdoHD.isSelected()) {
            tinhTrang = 1;
        } else {
            tinhTrang = 0;
        }
        KhachHang kh = new KhachHang(ma, ten, gioiTinh, ngaySinh, diaChi, sdt, 0, cccd, tinhTrang, email);
        if (service.create(kh)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            loadTable();
            return;
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại");
            return;
        }
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String ma = txtMa.getText();
        if (service.delete(ma)) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        loadTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        int gioiTinh = 1;
        if (rdoNam.isSelected()) {
            gioiTinh = 1;
        } else {
            gioiTinh = 0;
        }
        SimpleDateFormat dinhDang = new SimpleDateFormat("yyyy-MM-dd");
        String ngaySinh = dinhDang.format(txtNgaySinh.getDate());
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        String cccd = txtCCCD.getText();
        String diaChi = txtDiaChi.getText();
        int tinhTrang = 0;
        if (rdoHD.isSelected()) {
            tinhTrang = 1;
        } else {
            tinhTrang = 0;
        }
        KhachHang kh = new KhachHang(ma, ten, gioiTinh, ngaySinh, diaChi, sdt, 0, cccd, tinhTrang, email);
        if (service.update(kh)) {
            JOptionPane.showMessageDialog(this, "Update thành công");
            loadTable();
            
        } else {
            JOptionPane.showMessageDialog(this, "Update thất bại");
            return;
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnLamMoiActionPerformed
        Mail mail = new Mail();
        mail.setVisible(true);

    }//GEN-LAST:event_tbnLamMoiActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        try {
            int selectedRow = tblKhachHang.getSelectedRow();
            List<KhachHang> list = service.getAll();
            KhachHang s = list.get(selectedRow);
            if (selectedRow < 0) {
                return;
            }
            txtMa.setText(s.getMa());
            txtTen.setText(String.valueOf(s.getTen()));
            String ngaySinh=(String.valueOf(s.getNgaySinh()));
            java.util.Date ngay = new SimpleDateFormat("yyyy-MM-dd").parse(ngaySinh);
            txtNgaySinh.setDate(ngay);
            txtSDT.setText(String.valueOf(s.getSdt()));
            txtTen.setText(s.getTen());
            if (s.getGioiTinh() == 1) {
                rdoNam.setSelected(true);
            } else {
                rdoNu.setSelected(true);
            }
            txtEmail.setText(s.getEmail());
            txtCCCD.setText(s.getSoCMT());
            txtDiaChi.setText(s.getDiaChi());
            lblDiem.setText(String.valueOf(s.getDiemTichLuy()));
            if (s.getTinhTrang() == 1) {
                rdoHD.setSelected(true);
            } else {
                rdoKoHD.setSelected(true);
            }
        } catch (ParseException ex) {
            Logger.getLogger(QuanLyKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JRadioButton rdoHD;
    private javax.swing.JRadioButton rdoKoHD;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JButton tbnLamMoi;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMa;
    private com.toedter.calendar.JDateChooser txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
public String doiTT(int tt) {
        if (tt == 0) {
            return "Không hoạt động";
        }
        return "Hoạt động";
    }
}
